TEST husky

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,7 +1,13 @@
 #!/bin/sh
 
-# Get the test coverage
-coverage=$(npm run test:cov)
+# Run the tests with coverage and capture the output
+coverage=$(npm run test:cov | grep -oP '(?<=Coverage is ).*(?=%)')
+
+# Check if coverage value is empty
+if [ -z "$coverage" ]; then
+  echo "Failed to retrieve coverage percentage. Please check your test script."
+  exit 1
+fi
 
 echo "Coverage is $coverage%"
 
